--- #YAML:1.0
name:               metatap
version:            0.01
abstract:           Create TAP about TAP
author:
    - Patrick LeBoutillier <patl@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    TAP::Harness:   0
    Test::Builder:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
